pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('back/beauduck-board'){
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
                    sh 'docker build -t feat-back-board .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                        sh 'docker stop feat-back-board'
                        sh 'docker rm feat-back-board'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }

        }
        stage('Run New image') {
            steps {
                sh 'docker run --name feat-back-board -d -p 8081:8081 feat-back-board'
                echo 'Run New image'
            }
        }

    }
}
