pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('back/beauduck-makeup'){
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
                    sh 'docker build -t feat-back-makeup .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                            sh 'docker stop feat-back-makeup'
                            sh 'docker rm feat-back-makeup'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }

        }

        stage('Run New image') {
            steps {
                sh 'docker run --name feat-back-makeup -d -p 8082:8082 feat-back-makeup'
                echo 'Run New image'
            }
        }

    }
}
