pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                            sh 'docker stop feat-back-consult'
                            sh 'docker rm feat-back-consult'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('back/beauduck-consult'){
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
//                     sh 'docker-compose -f "docker-compose.yml" up -d --build'
                    sh 'docker build -t feat-back-consult .'
                }
                echo 'Build image...'
            }
        }

 

        stage('Run New image') {
            steps {
                sh 'docker run --name feat-back-consult -d -p 8083:8083 feat-back-consult'
                echo 'Run New image'
            }
        }

    }
}
