pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('openvidu-basic-java'){
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
                    sh 'docker build -t feat-back-openvidu .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                            sh 'docker stop feat-back-openvidu'
                            sh 'docker rm feat-back-openvidu'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }

        }
        stage('Run New image') {
            steps {
                sh 'docker run --name feat-back-openvidu -d -p 9000:9000 feat-back-openvidu'
                echo 'Run New image'
            }
        }

    }
}
